// SPDX-License-Identifier: BSL-1.1
// Copyright (c) 2026 Vestra Protocol. All rights reserved.
pragma solidity ^0.8.20;

import "./governance/VestraAccessControl.sol";

/**
 * @title IZkVerifier
 * @notice General interface for ZK-VM proof verification (e.g. RISC Zero, Bonsai).
 */
interface IZkVerifier {
    function verify(bytes calldata journal, bytes calldata seal) external view returns (bool);
}

/**
 * @title ZkAiAdapter
 * @notice Authenticates that Omega Agent risk parameters were generated by the 
 * authorized MeTTa ruleset using a ZK-VM proof.
 */
contract ZkAiAdapter is VestraAccessControl {
    address public verifier;
    bytes32 public authorizedImageId; // Hash of the compiled MeTTa binary/ruleset

    event ProofVerified(bytes32 indexed imageId, bytes journal);
    event VerifierUpdated(address indexed newVerifier);

    constructor(address _verifier, bytes32 _imageId, address _initialGovernor) VestraAccessControl(_initialGovernor) {
        verifier = _verifier;
        authorizedImageId = _imageId;
    }

    function setVerifier(address _verifier) external onlyGovernor {
        verifier = _verifier;
        emit VerifierUpdated(_verifier);
    }

    /**
     * @notice Verify a proof of MeTTa reasoning.
     * @param journal The output of the ZK-VM (e.g. [token, omega, timestamp])
     * @param seal The cryptographic proof
     */
    function verifyReasoning(bytes calldata journal, bytes calldata seal) external returns (bool) {
        // Enforce that only the authorized MeTTa 'Brain' can provide these proofs
        require(IZkVerifier(verifier).verify(journal, seal), "invalid ZK proof");
        
        emit ProofVerified(authorizedImageId, journal);
        return true;
    }
}
