const { normalizeAnyWalletAddress } = require('./lib/utils');
const addr = "0x39ecf94ed35451a67006dcce4a467aecdfab6940";
console.log("Input:", addr);
const out = normalizeAnyWalletAddress(addr);
console.log("Output:", out);
const addrChecksum = "0x39Ecf94ed35451A67006dcCE4A467aecdfAB6940";
console.log("Checksum Input:", addrChecksum);
const outChecksum = normalizeAnyWalletAddress(addrChecksum);
console.log("Checksum Output:", outChecksum);
if (out === outChecksum) console.log("MATCH SUCCESS");
else console.log("MATCH FAILURE");
